// Single source of truth for every sellable product.
// Add a new product by adding an entry here — product.html reads it via ?id=<key>,
// and the cart/checkout screens pull name/price/image from here too.
// "colors" can be left as [] for products that don't have a color choice —
// the color picker on the product page just won't show up.
const PRODUCTS = {
  "pushup-board": {
    name: "Foldable Push-Up Board Set",
    price: 19.00,
    images: [
      "images/pushup-board-temu-main.jpg",
      "images/pushup-board-ae.webp",
      "images/pushup-board-ae-2.webp",
      "images/pushup-board-ae-3.webp",
      "images/pushup-board-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A foldable multi-functional push-up board with handles — targets chest, shoulders, back, and triceps with color-coded hand positions, plus jump rope and resistance band accessories.",
  },
  "ab-roller": {
    name: "Ab Roller Wheel",
    price: 22.00,
    images: [
      "images/ab-roller-temu-main.jpg",
      "images/ab-roller-ae.webp",
      "images/ab-roller-ae-2.webp",
      "images/ab-roller-ae-3.webp",
      "images/ab-roller-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A wide-wheel ab roller with non-slip handles and a sturdy, durable build — lightweight and easy to store for everyday core workouts.",
  },
  "mens-polo": {
    name: "Contrast Collar Polo Shirt",
    price: 29.99,
    images: [
      "images/mens-polo-ae-2.webp",
      "images/mens-polo-ae.webp",
      "images/mens-polo-ae-3.webp",
      "images/mens-polo-ae-4.webp",
    ],
    sizes: ["M", "L", "XL", "XXL", "XXXL"],
    colors: ["Dark Blue", "Light Blue", "White"],
    colorImageIndex: { "Dark Blue": 0, "Light Blue": 1, "White": 2 },
    description: "A short-sleeve polo shirt with a contrast-striped collar and cuffs, front pocket, and breathable anti-wrinkle fabric — clean, business-casual style.",
  },
  "mens-shorts": {
    name: "Quick-Dry Zip Pocket Shorts",
    price: 24.99,
    images: [
      "images/mens-shorts-ae.png",
      "images/mens-shorts-ae-2.png",
      "images/mens-shorts-ae-3.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: [],
    description: "Quick-dry running and fitness shorts with a zip security pocket, drawstring waist, and mesh liner — built for training, not just lounging.",
  },
  "mens-knit-tee": {
    name: "Ribbed Knit Crew Neck Tee",
    price: 27.99,
    images: [
      "images/mens-knit-tee-ae.png",
      "images/mens-knit-tee-ae-2.png",
      "images/mens-knit-tee-ae-3.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: [],
    description: "A ribbed knit crew neck tee with a relaxed, draped fit — soft basic knitwear that layers well or wears alone.",
  },
  "mens-tshirt": {
    name: "Heavyweight Oversized Tee",
    price: 26.99,
    images: [
      "images/mens-tshirt-ae.png",
      "images/mens-tshirt-ae-2.png",
      "images/mens-tshirt-ae-3.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
    description: "A 280gsm heavyweight cotton oversized tee with a dropped shoulder — thick, structured fabric that holds its shape wash after wash.",
  },
  "mens-vintage-wash-tee": {
    name: "Vintage Wash Oversized Tee",
    price: 27.00,
    images: [
      "images/mens-vintage-wash-tee.png",
      "images/mens-vintage-wash-tee-2.png",
      "images/mens-vintage-wash-tee-3.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Gray", "Brown"],
    colorImageIndex: { "Green": 0, "Gray": 1, "Brown": 2 },
    description: "A garment-washed oversized tee with a faded, vintage look — loose drop-shoulder fit in soft, heavy cotton.",
  },
  "mens-classic-sweatpants": {
    name: "Classic Fit Sweatpants",
    price: 32.99,
    images: [
      "images/mens-classic-sweatpants-ae.webp",
      "images/mens-classic-sweatpants-ae-2.webp",
      "images/mens-classic-sweatpants-ae-3.webp",
      "images/mens-classic-sweatpants-ae-4.webp",
      "images/mens-classic-sweatpants-ae-5.webp",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: ["Maroon", "Black", "Grey", "Tan"],
    colorImageIndex: { "Maroon": 1, "Black": 3, "Grey": 0, "Tan": 4 },
    description: "A heavyweight fleece sweatpant in a classic straight fit with an elastic drawstring waist and ribbed cuffs — a wardrobe staple in four core colors.",
  },
  "mens-track-joggers": {
    name: "Quick-Dry Track Joggers",
    price: 28.99,
    images: [
      "images/mens-track-joggers-ae.webp",
      "images/mens-track-joggers-ae-2.webp",
      "images/mens-track-joggers-ae-3.webp",
      "images/mens-track-joggers-ae-4.webp",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Khaki", "Blue", "Black", "Navy"],
    description: "A slim tapered track pant in quick-dry stretch fabric with zip pockets and an elastic waist — built for running and gym days, sharp enough for the street.",
  },
  "mens-baggy-joggers": {
    name: "Baggy Ankle-Length Joggers",
    price: 27.99,
    images: [
      "images/mens-baggy-joggers-ae.webp",
      "images/mens-baggy-joggers-ae-2.webp",
      "images/mens-baggy-joggers-ae-3.webp",
      "images/mens-baggy-joggers-ae-4.webp",
    ],
    sizes: ["L", "XL", "XXL", "3XL", "4XL"],
    colors: ["Blue-Green", "Beige", "Black", "Navy"],
    description: "A lightweight, breathable baggy jogger with a cropped ankle-length cut — relaxed streetwear fit for warm-weather wear.",
  },
  "mens-fleece-joggers": {
    name: "Classic Fleece Joggers",
    price: 27.99,
    images: [
      "images/mens-fleece-joggers-ae.webp",
      "images/mens-fleece-joggers-ae-2.webp",
      "images/mens-fleece-joggers-ae-3.webp",
      "images/mens-fleece-joggers-ae-4.webp",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    colors: ["Black", "Charcoal", "Grey", "Navy", "White"],
    description: "A go-to fleece jogger with an elastic drawstring waist and ribbed cuffs — soft, roomy, and available in five everyday colors.",
  },
  "amber-spice": {
    name: "Amber Spice EDP",
    price: 29.00,
    images: [
      "images/amber-spice.png",
      "images/amber-spice-2.png",
      "images/amber-spice-3.png",
      "images/amber-spice-4.png",
      "images/amber-spice-5.png",
    ],
    sizes: [],
    colors: [],
    description: "A warm, woody-spicy amber scent with a bold, long-lasting trail. Inspired by Dior Sauvage.",
  },
  "citrus-cedar": {
    name: "Citrus Cedar Cologne",
    price: 32.00,
    images: [
      "images/citrus-cedar.png",
      "images/citrus-cedar-2.png",
      "images/citrus-cedar-3.png",
      "images/citrus-cedar-4.png",
    ],
    sizes: [],
    colors: [],
    description: "Crisp citrus over cedarwood and soft aromatic herbs, fresh and understated. Inspired by Chanel Bleu de Chanel.",
  },
  "aquatic-bergamot": {
    name: "Aquatic Bergamot EDP",
    price: 36.00,
    images: [
      "images/aquatic-bergamot.png",
      "images/aquatic-bergamot-2.png",
    ],
    sizes: [],
    colors: [],
    description: "A fresh, aquatic scent with bright bergamot and a clean marine finish. Inspired by Giorgio Armani Acqua di Gio.",
  },
  "club-de-nuit": {
    name: "Club de Nuit Iconic EDP, 3.6oz",
    price: 29.00,
    images: [
      "images/club-de-nuit-ae.webp",
      "images/club-de-nuit-ae-2.webp",
      "images/club-de-nuit-ae-3.webp",
      "images/club-de-nuit-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A bold, smoky-sweet eau de parfum with a rich, long-lasting trail — full 3.6oz bottle. Inspired by Creed Aventus.",
  },
  "mandarin-sky": {
    name: "Odyssey Mandarin Sky EDP, 3.4oz",
    price: 26.00,
    images: [
      "images/mandarin-sky-ae.webp",
      "images/mandarin-sky-ae-2.webp",
      "images/mandarin-sky-ae-3.webp",
    ],
    sizes: [],
    colors: [],
    description: "A bright, zesty mandarin-citrus eau de parfum with a warm, unisex base — full 3.4oz bottle in a distinctive travel-flask-style case.",
  },
  "dubai-chocolat": {
    name: "Odyssey Dubai Chocolat EDP, 3.4oz",
    price: 26.00,
    images: [
      "images/dubai-chocolat-ae.webp",
      "images/dubai-chocolat-ae-2.webp",
    ],
    sizes: [],
    colors: [],
    description: "A rich gourmand eau de parfum layered with cocoa, hazelnut, and warm spice — full 3.4oz bottle, alcohol-free formula.",
  },
  "club-de-nuit-untold": {
    name: "Club de Nuit Untold EDP, 3.6oz",
    price: 32.00,
    images: [
      "images/club-de-nuit-untold-ae.webp",
      "images/club-de-nuit-untold-ae-2.webp",
    ],
    sizes: [],
    colors: [],
    description: "A vibrant floral-fruity eau de parfum in an iridescent bottle, bold and long-lasting — full 3.6oz size.",
  },
  "yum-yum": {
    name: "Delights Yum Yum EDP, 3.4oz",
    price: 28.00,
    images: [
      "images/yum-yum-ae.webp",
    ],
    sizes: [],
    colors: [],
    description: "A sweet, fruity gourmand eau de parfum in a playful pink presentation — full 3.4oz bottle, alcohol-free formula.",
  },
  "hawas-pink": {
    name: "Hawas For Her Pink EDP, 3.4oz",
    price: 24.00,
    images: [
      "images/hawas-pink-ae.webp",
    ],
    sizes: [],
    colors: [],
    description: "A floral-fruity eau de parfum with a soft, long-lasting trail — full 100ml/3.4oz bottle, alcohol-free formula.",
  },
  "linen-shirt": {
    name: "Linen Short Sleeve Button Shirt",
    price: 29.99,
    images: [
      "images/linen-shirt.png",
      "images/linen-shirt-blue.png",
      "images/linen-shirt-black.png",
      "images/linen-shirt-gray.png",
      "images/linen-shirt-white.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: ["Beige", "Blue", "Black", "Gray", "White"],
    // Picking a color also jumps the photo slideshow to the matching image index.
    colorImageIndex: { "Beige": 0, "Blue": 1, "Black": 2, "Gray": 3, "White": 4 },
  },
  "led-face-mask": {
    name: "7-Color LED Light Therapy Face Mask",
    price: 29.00,
    images: [
      "images/led-face-mask.webp",
      "images/led-face-mask-2.webp",
      "images/led-face-mask-3.webp",
      "images/led-face-mask-4.webp",
      "images/led-face-mask-5.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 7-color LED light therapy mask for anti-aging, wrinkle reduction, and skin brightening — full-face coverage with adjustable light modes.",
  },
  "led-face-neck-mask": {
    name: "7-Color LED Face & Neck Mask",
    price: 49.00,
    images: [
      "images/led-face-neck-mask.webp",
      "images/led-face-neck-mask-2.webp",
      "images/led-face-neck-mask-3.webp",
    ],
    sizes: [],
    colors: [],
    description: "A wraparound 7-color LED photon therapy mask covering face and neck for firming, anti-aging, and skin rejuvenation.",
  },
  "cupping-massager": {
    name: "Electric Vacuum Cupping Massager",
    price: 24.00,
    images: [
      "images/cupping-massager.webp",
      "images/cupping-massager-2.webp",
      "images/cupping-massager-3.webp",
      "images/cupping-massager-4.webp",
      "images/cupping-massager-5.webp",
    ],
    sizes: [],
    colors: [],
    description: "A rechargeable electric vacuum cupping massager with 12 heat/suction gears and an LCD display — cupping and gua sha therapy for back, neck, and arms.",
  },
  "cupping-set": {
    name: "Cupping Therapy Set with Pump",
    price: 19.00,
    images: [
      "images/cupping-set-temu-main.jpg",
      "images/cupping-set.webp",
      "images/cupping-set-2.webp",
      "images/cupping-set-3.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 12-piece manual cupping therapy set with hand pump and carrying case — traditional cupping for muscle relief and circulation.",
  },
  "ice-roller": {
    name: "Cooling Ice Roller for Face",
    price: 18.00,
    images: [
      "images/ice-roller-temu-main.jpg",
      "images/ice-roller-ae.webp",
      "images/ice-roller-ae-2.webp",
      "images/ice-roller-ae-3.webp",
      "images/ice-roller-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A reusable cooling ice roller for the face — lifts and tightens skin, smooths puffiness and fine lines, safe for daily at-home use.",
  },
  "foam-roller": {
    name: "EPP Foam Roller",
    price: 24.00,
    images: [
      "images/foam-roller-temu-main.jpg",
      "images/foam-roller-ae.webp",
      "images/foam-roller-ae-2.webp",
      "images/foam-roller-ae-3.webp",
      "images/foam-roller-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A high-density EPP foam roller for pre- and post-workout muscle recovery — deep tissue massage for the back, legs, and full body after training or yoga.",
  },
  "pull-up-bar": {
    name: "Doorway Pull-Up Bar",
    price: 34.00,
    images: [
      "images/pull-up-bar-temu-main.jpg",
      "images/pull-up-bar-ae.webp",
      "images/pull-up-bar-ae-2.png",
      "images/pull-up-bar-ae-3.png",
    ],
    sizes: [],
    colors: [],
    description: "A sturdy steel doorway pull-up bar with adjustable width — no drilling required, for home upper-body strength training.",
  },
  "boxing-band": {
    name: "8-Shaped Boxing Resistance Band",
    price: 15.00,
    images: [
      "images/boxing-band-temu-main.jpg",
      "images/boxing-band-ae.webp",
      "images/boxing-band-ae-2.webp",
      "images/boxing-band-ae-3.webp",
      "images/boxing-band-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An 8-shaped tension resistance band with foam handles — for boxing, karate, Pilates, and full-body strength training at home or outdoors.",
  },
  "resistance-bands": {
    name: "11-Piece Resistance Bands Set",
    price: 22.00,
    images: [
      "images/resistance-bands-temu-main.jpg",
      "images/resistance-bands-ae.webp",
      "images/resistance-bands-ae-2.webp",
      "images/resistance-bands-ae-3.webp",
      "images/resistance-bands-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An 11-piece multifunctional TPE resistance band set with foam handles, door anchor, ankle strap, and carry bag — a complete home workout kit for beginners and beyond.",
  },
  "arm-trainer": {
    name: "U-Shaped Forearm Strength Trainer",
    price: 44.00,
    images: [
      "images/arm-trainer-temu-main.jpg",
      "images/arm-trainer-ae.webp",
      "images/arm-trainer-ae-2.webp",
      "images/arm-trainer-ae-3.webp",
      "images/arm-trainer-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An adjustable U-shaped forearm and chest strength trainer — detachable spring resistance bands (60-100lbs), comfortable grip, portable home gym equipment.",
  },
  "grip-strengthener": {
    name: "Adjustable Hand Grip Strengthener",
    price: 16.00,
    images: [
      "images/grip-strengthener-temu-main.jpg",
      "images/grip-strengthener-ae.webp",
      "images/grip-strengthener-ae-2.webp",
      "images/grip-strengthener-ae-3.webp",
      "images/grip-strengthener-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An adjustable hand grip strengthener with digital counter — builds forearm and wrist strength, resistance adjusts to match your hand size and training level.",
  },
  "nail-kit": {
    name: "9-Piece Professional Nail Care Kit",
    price: 22.00,
    images: [
      "images/nail-kit-temu-main.jpg",
      "images/nail-kit-ae.webp",
      "images/nail-kit-ae-2.webp",
      "images/nail-kit-ae-3.webp",
      "images/nail-kit-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 9-piece professional nail care kit with stainless steel cuticle pliers, nail clippers, and nail file in a sleek travel case — durable, precise hand care tools.",
  },
  "exfoliating-towel": {
    name: "Japanese Exfoliating Bath Towel",
    price: 14.00,
    images: [
      "images/exfoliating-towel-temu-main.jpg",
      "images/exfoliating-towel-ae.webp",
      "images/exfoliating-towel-ae-2.webp",
      "images/exfoliating-towel-ae-3.webp",
      "images/exfoliating-towel-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A Japanese-style exfoliating bath towel and back scrubber — long enough to reach every part of the back, for smoother, softer skin.",
  },
  "shower-brush-set": {
    name: "3-Piece Silicone Shower Brush Set",
    price: 19.00,
    images: [
      "images/shower-brush-set-temu-main.jpg",
      "images/shower-brush-set-ae.webp",
      "images/shower-brush-set-ae-2.webp",
      "images/shower-brush-set-ae-3.webp",
      "images/shower-brush-set-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 3-piece silicone shower brush set — long-handled body brush, facial cleansing brush, and scalp massager for deep cleaning and gentle daily massage.",
  },
  "makeup-sponge-set": {
    name: "20-Piece Makeup Sponge Set",
    price: 16.00,
    images: [
      "images/makeup-sponge-set-temu-main.jpg",
      "images/makeup-sponge-set-ae.webp",
      "images/makeup-sponge-set-ae-2.webp",
      "images/makeup-sponge-set-ae-3.webp",
      "images/makeup-sponge-set-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 20-piece makeup sponge set — cushion puffs, loose powder puffs, and blending sponges for flawless BB cream, foundation, and concealer application.",
  },
  "wireless-charger": {
    name: "3-in-1 Magnetic Wireless Charger",
    price: 24.00,
    images: [
      "images/wireless-charger-ae.webp",
      "images/wireless-charger-ae-2.webp",
      "images/wireless-charger-ae-3.webp",
      "images/wireless-charger-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A magnetic 3-in-1 wireless charging stand for phone, watch, and earbuds — fast 30W charging, foldable and travel-friendly.",
  },
  "neck-fan": {
    name: "Rechargeable Bladeless Neck Fan",
    price: 19.00,
    images: [
      "images/neck-fan-ae.webp",
      "images/neck-fan-ae-2.webp",
      "images/neck-fan-ae-3.webp",
      "images/neck-fan-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A wearable bladeless neck fan with 8000mAh battery, LED display, and quiet 360° airflow — hands-free cooling for commuting, workouts, or outdoor days.",
  },
  "earbuds": {
    name: "Sport Wireless Earbuds",
    price: 34.00,
    images: [
      "images/earbuds-ae.png",
      "images/earbuds-ae-2.png",
      "images/earbuds-ae-3.png",
    ],
    sizes: [],
    colors: [],
    description: "Sport wireless earbuds with LED power display, HiFi stereo sound, and a secure sweat-resistant fit — built-in mics for hands-free calls.",
  },
  "bt-speaker": {
    name: "Portable Bluetooth Speaker",
    price: 28.00,
    images: [
      "images/bt-speaker-ae.png",
      "images/bt-speaker-ae-2.png",
      "images/bt-speaker-ae-3.png",
    ],
    sizes: [],
    colors: [],
    description: "A portable wireless Bluetooth speaker with rich bass and long battery life — compact enough for travel, powerful enough for outdoor gatherings.",
  },
  "charging-cable": {
    name: "3-in-1 Fast Charging Cable",
    price: 14.00,
    images: [
      "images/charging-cable-ae.webp",
      "images/charging-cable-ae-2.webp",
      "images/charging-cable-ae-3.webp",
      "images/charging-cable-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 3-in-1 fast charging cable with USB-C, Lightning, and Micro-USB connectors — 100W/6A rapid charging and data transfer in one braided cord.",
  },
  "projector": {
    name: "Mini Portable Projector",
    price: 59.00,
    images: [
      "images/projector-ae.webp",
      "images/projector-ae-2.webp",
      "images/projector-ae-3.webp",
      "images/projector-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A mini portable home theater projector with native HD resolution and built-in Android smart OS — stream movies and shows on a screen up to 200 inches.",
  },
  "smart-tag": {
    name: "Smart Bluetooth Item Tracker",
    price: 17.00,
    images: [
      "images/smart-tag-ae.png",
      "images/smart-tag-ae-2.png",
      "images/smart-tag-ae-3.png",
    ],
    sizes: [],
    colors: [],
    description: "A Bluetooth item tracker compatible with Apple Find My — waterproof, loud alarm, and precision location finding for keys, bags, and more.",
  },
  "power-bank": {
    name: "Magnetic Wireless Power Bank",
    price: 54.00,
    images: [
      "images/power-bank-ae.webp",
      "images/power-bank-ae-2.webp",
      "images/power-bank-ae-3.webp",
      "images/power-bank-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A slim magnetic wireless power bank — 15W wireless and 20W wired charging, snaps securely to your phone for charge-on-the-go.",
  },
  "lined-tank-top": {
    name: "Lined Tank Top",
    price: 15.99,
    images: [
      "images/lined-tank-top.png",
      "images/lined-tank-top-green.png",
      "images/lined-tank-top-coffee.png",
      "images/lined-tank-top-black.png",
      "images/lined-tank-top-darkgrey.png",
      "images/lined-tank-top-white.png",
      "images/lined-tank-top-grey.png",
      "images/lined-tank-top-pink.png",
      "images/lined-tank-top-blue.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Brown", "Green", "Coffee", "Black", "Dark Grey", "White", "Grey", "Pink", "Blue"],
    // Picking a color also jumps the photo slideshow to the matching image index.
    colorImageIndex: {
      "Brown": 0, "Green": 1, "Coffee": 2, "Black": 3, "Dark Grey": 4,
      "White": 5, "Grey": 6, "Pink": 7, "Blue": 8,
    },
  },
  "womens-quickdry-tank": {
    name: "UPF 80+ Quick Dry Tank Top",
    price: 22.00,
    images: [
      "images/womens-quickdry-tank-ae.webp",
      "images/womens-quickdry-tank-ae-2.webp",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
    description: "A quick-dry, moisture-wicking tank top with UPF 80+ UV protection and a tie-back open design — built for yoga, running, and hot-weather wear.",
  },
  "womens-mesh-tank": {
    name: "Mesh Racerback Workout Tank",
    price: 24.00,
    images: [
      "images/womens-mesh-tank-ae.webp",
      "images/womens-mesh-tank-ae-2.webp",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
    description: "A lightweight mesh racerback tank with a high-low curved hem — breathable, quick-dry, and built for yoga or everyday wear.",
  },
  "womens-tube-top": {
    name: "Strapless Tube Top",
    price: 26.00,
    images: [
      "images/womens-tube-top-ae.webp",
      "images/womens-tube-top-ae-2.webp",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    description: "A strapless, shock-absorbing tube top with a seamless quick-dry finish — stays securely in place for workouts or worn casually on its own.",
  },
  "womens-lace-tank": {
    name: "Y2K Lace Trim Ribbed Tank",
    price: 24.00,
    images: [
      "images/womens-lace-tank-ae.webp",
    ],
    sizes: [],
    colors: [],
    description: "A ribbed cotton-blend tank with delicate lace trim and a button placket — sweet, vintage-inspired Y2K styling, one size fits most.",
  },
  "womens-hooded-crop-tank": {
    name: "Hooded Eyelet Crop Tank",
    price: 20.00,
    images: [
      "images/womens-hooded-crop-tank-ae.webp",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [],
    description: "A sleeveless hooded crop tank with eyelet ring detailing and a cowl neck — gothic Y2K streetwear styling.",
  },
  "satin-pajama-set": {
    name: "Satin Pajama Set",
    price: 32.00,
    images: [
      "images/satin-pajama-set.jpg",
      "images/satin-pajama-set-2.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    description: "A button-down satin pajama top and shorts set with contrast piping and a bow-tie waistband — smooth, breathable sleepwear for warm nights.",
  },
  "flare-leggings": {
    name: "Cross-Waist Flare Leggings",
    price: 34.00,
    images: [
      "images/flare-leggings.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
    description: "Super-soft crossover high-waisted flare leggings with a side phone pocket and tummy-control fit — built for yoga, running, or everyday wear.",
  },
  "teen-star-cargo-jeans": {
    name: "Star Patch Wide-Leg Cargo Jeans",
    price: 29.00,
    images: [
      "images/teen-star-cargo-jeans.png",
      "images/teen-star-cargo-jeans-2.png",
    ],
    sizes: ["9-10Y", "11-12Y"],
    colors: [],
    description: "Wide-leg denim jeans with an elastic waist and star patch detailing at the knees and thighs — a trendy streetwear staple.",
  },
  "teen-lace-cargo-jeans": {
    name: "Lace Patch Wide-Leg Jeans",
    price: 34.00,
    images: [
      "images/teen-lace-cargo-jeans.png",
      "images/teen-lace-cargo-jeans-2.png",
    ],
    sizes: ["5Y", "7Y", "9Y", "11Y", "13Y", "14Y"],
    colors: [],
    description: "Oversized wide-leg ripped jeans with floral lace patches and a drawstring waist sash — bold Y2K streetwear styling.",
  },
  "teen-cargo-sweatpants": {
    name: "Oversized Cargo Sweatpants",
    price: 26.00,
    images: [
      "images/teen-cargo-sweatpants.png",
    ],
    sizes: ["5T", "6T", "7-8T", "9-10T", "11-12T", "13-14T"],
    colors: ["Gray", "Purple", "Black"],
    colorImageIndex: { "Gray": 0, "Purple": 0, "Black": 0 },
    description: "Loose workwear-style cargo sweatpants with an elastic drawstring waist and side pockets — lightweight and easy to move in.",
  },
  "teen-acid-wash-tee": {
    name: "Y2K Acid Washed Graphic Tee",
    price: 28.00,
    images: [
      "images/teen-acid-wash-tee.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
    description: "An acid-washed oversized tee with a gothic graphic print — soft cotton with a vintage, worn-in streetwear look.",
  },
  "teen-swag-tank": {
    name: "#SWAG Ribbed Tank Top",
    price: 19.00,
    images: [
      "images/teen-swag-tank.png",
    ],
    sizes: ["S", "M", "L"],
    colors: [],
    description: "A ribbed cotton tank top with a bold #SWAG graphic — grunge Y2K style with a slim, cropped fit.",
  },
  "teen-dragon-tee": {
    name: "Dragon & Tiger Graphic Tee",
    price: 27.00,
    images: [
      "images/teen-dragon-tee.png",
    ],
    sizes: ["S(4)", "M(6)", "L(8/10)", "XL(12)"],
    colors: [],
    description: "A vintage-style graphic tee with a dragon and tiger print — 2000s Harajuku streetwear inspired.",
  },
  "kids-cartoon-tee": {
    name: "Cartoon Print Kids Tee",
    price: 14.00,
    images: [
      "images/kids-cartoon-tee-ae.webp",
    ],
    sizes: ["9M", "12M", "18M", "24M", "3T", "4T", "5T", "6T", "7T"],
    colors: [],
    description: "A soft cotton crewneck tee with a playful cartoon print — simple, comfortable everyday basic for kids.",
  },
  "kids-dino-polo": {
    name: "Dinosaur Print Kids Polo",
    price: 22.00,
    images: [
      "images/kids-dino-polo-ae.webp",
    ],
    sizes: ["24M", "3T", "4T", "5T", "6T", "7T", "8T", "9T"],
    colors: [],
    description: "A breathable cotton polo with an all-over dinosaur print — moisture-wicking and anti-wrinkle for all-day play.",
  },
  "kids-mandarin-shirt": {
    name: "Mandarin Collar Kids Shirt",
    price: 26.00,
    images: [
      "images/kids-mandarin-shirt-ae.webp",
    ],
    sizes: ["2T", "3T", "4T", "6", "8", "10"],
    colors: [],
    description: "A cotton-blend short-sleeve shirt with a mandarin collar — a clean, dressier option for special occasions.",
  },
  "kids-tank-top": {
    name: "Cartoon Print Kids Tank Top",
    price: 12.00,
    images: [
      "images/kids-tank-top-ae.webp",
    ],
    sizes: ["12M", "24M", "3T", "4T", "6T", "8T", "10T"],
    colors: [],
    description: "A 100% cotton sleeveless tank with a playful cartoon print — lightweight and breathable for hot-weather wear.",
  },
  "womens-sweat-shorts": {
    name: "Loose Fit Elastic Waist Sweat Shorts",
    price: 24.99,
    images: [
      "images/womens-sweat-shorts-ae.png",
      "images/womens-sweat-shorts-ae-2.png",
      "images/womens-sweat-shorts-ae-3.png",
      "images/womens-sweat-shorts-ae-4.png",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    description: "Breathable soft-knit sweat shorts with an elastic waist, side pockets, and a loose, relaxed fit — casual all-match style for running or lounging.",
  },
  "womens-yoga-shorts": {
    name: "Running Workout Yoga Shorts",
    price: 27.00,
    images: [
      "images/womens-yoga-shorts-white.png",
      "images/womens-yoga-shorts-black.png",
      "images/womens-yoga-shorts-lightblue.png",
      "images/womens-yoga-shorts-pink.png",
    ],
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Light Blue", "Pink"],
    colorImageIndex: { "White": 0, "Black": 1, "Light Blue": 2, "Pink": 3 },
    description: "Elastic-waist running and gym shorts with a built-in liner and dolphin hem — lightweight, quick-dry fabric for yoga, workouts, or everyday wear.",
  },
  "womens-scrunch-shorts": {
    name: "Scrunch Butt Biker Shorts",
    price: 26.00,
    images: [
      "images/womens-scrunch-shorts-black.png",
      "images/womens-scrunch-shorts-pink.png",
      "images/womens-scrunch-shorts-navy.png",
      "images/womens-scrunch-shorts-red.png",
      "images/womens-scrunch-shorts-lightblue.png",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Pink", "Navy", "Red", "Light Blue"],
    colorImageIndex: { "Black": 0, "Pink": 1, "Navy": 2, "Red": 3, "Light Blue": 4 },
    description: "Seamless low-waist biker shorts with a scrunch-back seam for a lifted fit — buttery-soft stretch fabric built for the gym or athleisure wear.",
  },
  "kids-striped-polo": {
    name: "Striped Kids Polo Shirt",
    price: 20.00,
    images: [
      "images/kids-striped-polo-ae.webp",
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8", "9", "10", "11", "12"],
    colors: [],
    description: "A classic striped polo shirt — soft, durable fabric built for school, beach days, or everyday wear.",
  },
};
