// Single source of truth for every sellable product.
// Add a new product by adding an entry here — product.html reads it via ?id=<key>,
// and the cart/checkout screens pull name/price/image from here too.
// "colors" can be left as [] for products that don't have a color choice —
// the color picker on the product page just won't show up.
const PRODUCTS = {
  hoodie: {
    name: "Heavyweight Oversized Hoodie",
    price: 44.00,
    images: ["images/hoodie.png", "images/hoodie-2.jpg", "images/hoodie-3.jpg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    // Picking a color also jumps the photo slideshow to the matching image index.
    colorImageIndex: { "Blue": 0, "Black": 1 },
  },
  "amber-spice": {
    name: "Amber Spice EDP",
    price: 29.00,
    images: [],
    sizes: [],
    colors: [],
    description: "A warm, woody-spicy amber scent with a bold, long-lasting trail. Inspired by Dior Sauvage.",
  },
  "citrus-cedar": {
    name: "Citrus Cedar Cologne",
    price: 32.00,
    images: [],
    sizes: [],
    colors: [],
    description: "Crisp citrus over cedarwood and soft aromatic herbs, fresh and understated. Inspired by Chanel Bleu de Chanel.",
  },
  "aquatic-bergamot": {
    name: "Aquatic Bergamot EDP",
    price: 36.00,
    images: [],
    sizes: [],
    colors: [],
    description: "A fresh, aquatic scent with bright bergamot and a clean marine finish. Inspired by Giorgio Armani Acqua di Gio.",
  },
  "linen-shirt": {
    name: "Linen Short Sleeve Button Shirt",
    price: 29.99,
    images: [
      "images/linen-shirt.png",
      "images/linen-shirt-blue.png",
      "images/linen-shirt-black.png",
      "images/linen-shirt-gray.png",
      "images/linen-shirt-white.png",
    ],
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: ["Beige", "Blue", "Black", "Gray", "White"],
    // Picking a color also jumps the photo slideshow to the matching image index.
    colorImageIndex: { "Beige": 0, "Blue": 1, "Black": 2, "Gray": 3, "White": 4 },
  },
  "led-face-mask": {
    name: "7-Color LED Light Therapy Face Mask",
    price: 29.00,
    images: [
      "images/led-face-mask.webp",
      "images/led-face-mask-2.webp",
      "images/led-face-mask-3.webp",
      "images/led-face-mask-4.webp",
      "images/led-face-mask-5.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 7-color LED light therapy mask for anti-aging, wrinkle reduction, and skin brightening — full-face coverage with adjustable light modes.",
  },
  "led-face-neck-mask": {
    name: "7-Color LED Face & Neck Mask",
    price: 49.00,
    images: [
      "images/led-face-neck-mask.webp",
      "images/led-face-neck-mask-2.webp",
      "images/led-face-neck-mask-3.webp",
    ],
    sizes: [],
    colors: [],
    description: "A wraparound 7-color LED photon therapy mask covering face and neck for firming, anti-aging, and skin rejuvenation.",
  },
  "cupping-massager": {
    name: "Electric Vacuum Cupping Massager",
    price: 24.00,
    images: [
      "images/cupping-massager.webp",
      "images/cupping-massager-2.webp",
      "images/cupping-massager-3.webp",
      "images/cupping-massager-4.webp",
      "images/cupping-massager-5.webp",
    ],
    sizes: [],
    colors: [],
    description: "A rechargeable electric vacuum cupping massager with 12 heat/suction gears and an LCD display — cupping and gua sha therapy for back, neck, and arms.",
  },
  "cupping-set": {
    name: "Cupping Therapy Set with Pump",
    price: 19.00,
    images: [
      "images/cupping-set-temu-main.jpg",
      "images/cupping-set.webp",
      "images/cupping-set-2.webp",
      "images/cupping-set-3.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 12-piece manual cupping therapy set with hand pump and carrying case — traditional cupping for muscle relief and circulation.",
  },
  "ice-roller": {
    name: "Cooling Ice Roller for Face",
    price: 18.00,
    images: [
      "images/ice-roller-temu-main.jpg",
      "images/ice-roller-ae.webp",
      "images/ice-roller-ae-2.webp",
      "images/ice-roller-ae-3.webp",
      "images/ice-roller-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A reusable cooling ice roller for the face — lifts and tightens skin, smooths puffiness and fine lines, safe for daily at-home use.",
  },
  "foam-roller": {
    name: "EPP Foam Roller",
    price: 24.00,
    images: [
      "images/foam-roller-temu-main.jpg",
      "images/foam-roller-ae.webp",
      "images/foam-roller-ae-2.webp",
      "images/foam-roller-ae-3.webp",
      "images/foam-roller-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A high-density EPP foam roller for pre- and post-workout muscle recovery — deep tissue massage for the back, legs, and full body after training or yoga.",
  },
  "pull-up-bar": {
    name: "Doorway Pull-Up Bar",
    price: 34.00,
    images: [
      "images/pull-up-bar-temu-main.jpg",
      "images/pull-up-bar-ae.webp",
      "images/pull-up-bar-ae-2.png",
      "images/pull-up-bar-ae-3.png",
    ],
    sizes: [],
    colors: [],
    description: "A sturdy steel doorway pull-up bar with adjustable width — no drilling required, for home upper-body strength training.",
  },
  "boxing-band": {
    name: "8-Shaped Boxing Resistance Band",
    price: 15.00,
    images: [
      "images/boxing-band-temu-main.jpg",
      "images/boxing-band-ae.webp",
      "images/boxing-band-ae-2.webp",
      "images/boxing-band-ae-3.webp",
      "images/boxing-band-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An 8-shaped tension resistance band with foam handles — for boxing, karate, Pilates, and full-body strength training at home or outdoors.",
  },
  "resistance-bands": {
    name: "11-Piece Resistance Bands Set",
    price: 22.00,
    images: [
      "images/resistance-bands-temu-main.jpg",
      "images/resistance-bands-ae.webp",
      "images/resistance-bands-ae-2.webp",
      "images/resistance-bands-ae-3.webp",
      "images/resistance-bands-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An 11-piece multifunctional TPE resistance band set with foam handles, door anchor, ankle strap, and carry bag — a complete home workout kit for beginners and beyond.",
  },
  "arm-trainer": {
    name: "U-Shaped Forearm Strength Trainer",
    price: 44.00,
    images: [
      "images/arm-trainer-temu-main.jpg",
      "images/arm-trainer-ae.webp",
      "images/arm-trainer-ae-2.webp",
      "images/arm-trainer-ae-3.webp",
      "images/arm-trainer-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An adjustable U-shaped forearm and chest strength trainer — detachable spring resistance bands (60-100lbs), comfortable grip, portable home gym equipment.",
  },
  "grip-strengthener": {
    name: "Adjustable Hand Grip Strengthener",
    price: 16.00,
    images: [
      "images/grip-strengthener-temu-main.jpg",
      "images/grip-strengthener-ae.webp",
      "images/grip-strengthener-ae-2.webp",
      "images/grip-strengthener-ae-3.webp",
      "images/grip-strengthener-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "An adjustable hand grip strengthener with digital counter — builds forearm and wrist strength, resistance adjusts to match your hand size and training level.",
  },
  "nail-kit": {
    name: "9-Piece Professional Nail Care Kit",
    price: 22.00,
    images: [
      "images/nail-kit-temu-main.jpg",
      "images/nail-kit-ae.webp",
      "images/nail-kit-ae-2.webp",
      "images/nail-kit-ae-3.webp",
      "images/nail-kit-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 9-piece professional nail care kit with stainless steel cuticle pliers, nail clippers, and nail file in a sleek travel case — durable, precise hand care tools.",
  },
  "exfoliating-towel": {
    name: "Japanese Exfoliating Bath Towel",
    price: 14.00,
    images: [
      "images/exfoliating-towel-temu-main.jpg",
      "images/exfoliating-towel-ae.webp",
      "images/exfoliating-towel-ae-2.webp",
      "images/exfoliating-towel-ae-3.webp",
      "images/exfoliating-towel-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A Japanese-style exfoliating bath towel and back scrubber — long enough to reach every part of the back, for smoother, softer skin.",
  },
  "shower-brush-set": {
    name: "3-Piece Silicone Shower Brush Set",
    price: 19.00,
    images: [
      "images/shower-brush-set-temu-main.jpg",
      "images/shower-brush-set-ae.webp",
      "images/shower-brush-set-ae-2.webp",
      "images/shower-brush-set-ae-3.webp",
      "images/shower-brush-set-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 3-piece silicone shower brush set — long-handled body brush, facial cleansing brush, and scalp massager for deep cleaning and gentle daily massage.",
  },
  "makeup-sponge-set": {
    name: "20-Piece Makeup Sponge Set",
    price: 16.00,
    images: [
      "images/makeup-sponge-set-temu-main.jpg",
      "images/makeup-sponge-set-ae.webp",
      "images/makeup-sponge-set-ae-2.webp",
      "images/makeup-sponge-set-ae-3.webp",
      "images/makeup-sponge-set-ae-4.webp",
    ],
    sizes: [],
    colors: [],
    description: "A 20-piece makeup sponge set — cushion puffs, loose powder puffs, and blending sponges for flawless BB cream, foundation, and concealer application.",
  },
  "lined-tank-top": {
    name: "Lined Tank Top",
    price: 15.99,
    images: [
      "images/lined-tank-top.png",
      "images/lined-tank-top-green.png",
      "images/lined-tank-top-coffee.png",
      "images/lined-tank-top-black.png",
      "images/lined-tank-top-darkgrey.png",
      "images/lined-tank-top-white.png",
      "images/lined-tank-top-grey.png",
      "images/lined-tank-top-pink.png",
      "images/lined-tank-top-blue.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Brown", "Green", "Coffee", "Black", "Dark Grey", "White", "Grey", "Pink", "Blue"],
    // Picking a color also jumps the photo slideshow to the matching image index.
    colorImageIndex: {
      "Brown": 0, "Green": 1, "Coffee": 2, "Black": 3, "Dark Grey": 4,
      "White": 5, "Grey": 6, "Pink": 7, "Blue": 8,
    },
  },
};
